apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
  namespace: monitoring
spec:
  groups:
    - name: basic
      rules:
        - alert: NodeDown
          expr: up == 0
          for: 2m
