apiVersion: observability.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      observability-root:observability.coreos.com/PrometheusRule:observability/alerts
  name: alerts
  namespace: observability
spec:
  groups:
    - name: basic
      rules:
        - alert: NodeDown
          expr: up == 0
          for: 2m

