apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability-root:argoproj.io/Application:argocd/alerts
    argocd.argoproj.io/sync-wave: "1"
  name: alerts
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    path: clusters/observability/apps/alerts
    repoURL: https://github.com/baona1109/gitops-observability
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

