apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: observability
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:LXb8lsm+KigSGiOUo5A=,iv:ibrfmrwTcKzD6z/mTdD9smltPe8cc3FfxFYMAErMo0g=,tag:la0Hazgl88RPMpckOFL04Q==,type:str]
sops:
    age:
        - recipient: age1yr02hy2pws3amhzjgf5tn2yfc3w2ec5afj8lafe5s8uvcnvdwalqx3w64t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbDlkQ1VaNG5KSXFyMWV5
            VWhFdXE1NlMvOTVTZlRMSk1uQlJHMVhCYzBZCm9Ocm5CakJFaTRpWE96QWRoOUNz
            NTFlWnBnTW1vOGU1YlgxYXF5UGtFdEkKLS0tIG4yYms2YzRMaUduRnVKUzBBckdE
            bEZua1AweEV2L0JvMnpFd1M0V3dsRHMK6Z4jsRxhOMpKEWN/CBw2ljpZtn7qqW/S
            qCdccSC9YnTQN7+PUfYVqu8WjqWSmBABwEhwQCxL1bXABiSSZ6gz0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T16:49:03Z"
    mac: ENC[AES256_GCM,data:+sQU4rShcRQqXquuQZyk3ScR3wptG9KMzqdFduSFq7n9QuUpj33D3q8VtJEwB+sgboQMjz4bUtphWdR0ijIJFV5xVXNgXHEGlX+e6vEFxEgpOljmvhmgEnjYi2Nkt5MWnhUMA6BhpuaSG8iXCxoIKM+vVpXqkjfgQ9td0uJPQ2c=,iv:cJDlEs8mdecnTIucb35MpCPegMZRT2ffhqVsHYUlcE4=,tag:4r5vfz+nS7lhxMaFp96T7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2