apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability-root:argoproj.io/Application:argocd/jaeger
  name: jaeger
  namespace: argocd
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    chart: jaeger
    helm:
      values: |
        storage:
          type: memory
        allInOne:
          enabled: true
        collector:
          enabled: false
        query:
          enabled: false
        agent:
          enabled: false
        cassandra:
          enabled: false
        provisionDataStore:
          cassandra: false
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

