apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    chart: jaeger
    helm:
      values: |
        storage:
          type: memory
        allInOne:
          enabled: true
          service:
            type: NodePort
            nodePort: 30686
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 0.71.0
  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /automountServiceAccountToken
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
