apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability-root:argoproj.io/Application:argocd/loki
  name: loki
  namespace: argocd
spec:
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: loki-loki-stack
      jsonPointers:
        - /data
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    helm:
      values: |
        grafana:
          enabled: false
        prometheus:
          enabled: false
        loki:
          isDefault: false
          sidecar:
            datasources:
              enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

