apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability-root:argoproj.io/Application:argocd/prometheus
    argocd.argoproj.io/sync-wave: "0"
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      skipCrds: false
      values: |
        grafana:
          adminPassword: admin
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.observability.svc:3100
              access: proxy
              version: 1
              isDefault: false
              editable: true
          sidecar:
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                cpu: 100m
                memory: 100Mi
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        prometheus:
          prometheusSpec:
            retention: 7d
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 58.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
