apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        crds:
          upgradeJob:
            enabled: false
        grafana:
          adminPassword: admin
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.observability.svc:3100
              access: proxy
              version: 1
              isDefault: false
              editable: true
          sidecar:
            datasources:
              enabled: true
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: observability
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                cpu: 100m
                memory: 100Mi
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          service:
            type: NodePort
            nodePort: 30300
        prometheus-node-exporter:
          prometheus:
            monitor:
              relabelings:
                - targetLabel: cluster
                  replacement: obs
        kubeStateMetrics:
          serviceMonitor:
            relabelings:
              - targetLabel: cluster
                replacement: obs
        alertmanager:
          service:
            type: NodePort
            nodePort: 30903
        prometheus:
          service:
            type: NodePort
            nodePort: 30090
          prometheusSpec:
            retention: 7d
            enableRemoteWriteReceiver: true
            externalLabels:
              cluster: obs
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 84.1.2
  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /automountServiceAccountToken
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true