resources:
  - apps/local-path-provisioner.yaml
  - apps/prometheus.yaml
  - apps/loki.yaml
  - apps/jaeger.yaml
  - apps/alerts-app.yaml
  - apps/argocd-config.yaml
  - apps/argocd-nodeport.yaml
  - apps/loki-nodeport.yaml
  - apps/grafana-dashboards/prod-overview.yaml
  - apps/grafana-dashboards/k8s-monitor.yaml
