resources:
  - apps/prometheus.yaml
  - apps/loki.yaml
  - apps/jaeger.yaml
  - apps/alerts-app.yaml

  - apps/ingress/grafana-ingress.yaml
  - apps/ingress/prometheus-ingress.yaml
  - apps/ingress/jaeger-ingress.yaml
  - apps/ingress/argocd-ingress.yaml
