apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability-root:networking.k8s.io/Ingress:observability/jaeger
      # cert-manager.io/cluster-issuer: "letsencrypt"
  name: jaeger
  namespace: observability
spec:
  ingressClassName: nginx
  rules:
    - host: jaeger.sudocrew.io.vn
      http:
        paths:
          - backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - jaeger.sudocrew.io.vn
      secretName: wildcard-tls

