apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observability-root:networking.k8s.io/Ingress:observability/prometheus
      # cert-manager.io/cluster-issuer: "letsencrypt"
  name: prometheus
  namespace: observability
spec:
  ingressClassName: nginx
  rules:
    - host: prometheus.sudocrew.io.vn
      http:
        paths:
          - backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - prometheus.sudocrew.io.vn
      secretName: wildcard-cert

