apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alerts
  namespace: observability
spec:
  groups:
    - name: basic
      rules:
        - alert: NodeDown
          expr: up{job="node-exporter"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Node {{ $labels.instance }} is down"