apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: arp-static
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: arp-static
  template:
    metadata:
      labels:
        app: arp-static
    spec:
      hostNetwork: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: arp
          image: busybox
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - arp -s 192.168.1.161 bc:24:11:c3:c3:d8
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.1
