apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-agent
  namespace: argocd
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 84.1.2
    helm:
      values: |
        prometheus:
          prometheusSpec:
            remoteWrite:
              - url: https://prometheus.sudocrew.io.vn/api/v1/write
                writeRelabelConfigs:
                  - targetLabel: cluster
                    replacement: prod
        grafana:
          enabled: false
        alertmanager:
          enabled: false
        prometheusOperator:
          enabled: true    # ← keep operator to install CRDs
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: true
        prometheus-node-exporter:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      jsonPointers:
        - /automountServiceAccountToken
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true    # ← fixes the annotation size error
